# Generated by Django 4.1.2 on 2022-11-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='share',
            options={'ordering': ['-id']},
        ),
    ]
