# Generated by Django 4.1.2 on 2022-11-03 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_share_timestamp_sharelike_share_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='friends.share'),
        ),
    ]
